# Generated by Django 4.2.13 on 2024-06-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_clients_status_alter_clients_adresse_communion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='adresse_email',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='horodateur',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='lieu_date_de_naissance',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='nom_postnom_et_prenom',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='profession',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
